#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# set left-handed mouse
for id in `/usr/bin/xinput list | /bin/grep 'Mouse' | /bin/grep -o '[0-9][0-9]'`; do
    xinput set-button-map $id 3 2 1;
done;

# numlock on
numlockx on

# keybindings
~/.config/herbstluftwm/keybindings.sh

# theme
~/.config/herbstluftwm/theme.sh

# rules
~/.config/herbstluftwm/rules.sh

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# monitor setup 
~/.config/herbstluftwm/monitors.sh

# panel setup
~/.config/herbstluftwm/panel.sh &

# start tag change listener, for opening apps on scratchpad
pkill -f 'tag_changed_listener.sh'
~/.config/herbstluftwm/tag_changed_listener.sh &

# autostart applications
lxsession &
picom &
nm-applet &
caffeine &
eww daemon &
[ -z "$(pgrep 'transmission')" ] && transmission-gtk -m &
